### ISSUE TITLE
ProgrammingError: operator does not exist: text = integerLINE 1: ...mment',null,description,0 FROM attachment WHERE id=327 ORDER...                                                             ^HINT:  No operator matches the given name and argument type(s)

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments-migration-test#111]
(Original issue 332 created by None on 2008-06-05T09:14:44+00:00)

==== How to Reproduce ====

While doing a GET operation on `/ticket/327`, Trac issued an internal error.

''(please provide additional details here)''

Request parameters:
{{{
{'id': u'327'}
}}}

==== System Information ====

|| '''Trac''' || `0.11dev-r6122` ||
|| '''Python''' || `2.5.2 (r252:60911, Apr 21 2008, 11:38:26) ` [[br]] `[GCC 4.2.3 (Ubuntu 4.2.3-2ubuntu7)]` ||
|| '''setuptools''' || `0.6c5` ||
|| '''psycopg2''' || `2.0.6` ||
|| '''Genshi''' || `0.4.3` ||
|| '''Pygments''' || `None` ||
|| '''Mercurial''' || `0.9.5` ||

==== Python Traceback ====
{{{
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.11dev_r6122-py2.5.egg/trac/web/main.py", line 381, in dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.11dev_r6122-py2.5.egg/trac/web/main.py", line 191, in dispatch
    resp = chosen_handler.process_request(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.11dev_r6122-py2.5.egg/trac/ticket/web_ui.py", line 154, in process_request
    return self._process_ticket_request(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.11dev_r6122-py2.5.egg/trac/ticket/web_ui.py", line 452, in _process_ticket_request
    field_changes)
  File "/usr/lib/python2.5/site-packages/Trac-0.11dev_r6122-py2.5.egg/trac/ticket/web_ui.py", line 1004, in _insert_ticket_data
    for change in self.rendered_changelog_entries(context):
  File "/usr/lib/python2.5/site-packages/Trac-0.11dev_r6122-py2.5.egg/trac/ticket/web_ui.py", line 1099, in rendered_changelog_entries
    when):
  File "/usr/lib/python2.5/site-packages/Trac-0.11dev_r6122-py2.5.egg/trac/ticket/web_ui.py", line 1163, in grouped_changelog_entries
    changelog = ticket.get_changelog(when=when, db=db)
  File "/usr/lib/python2.5/site-packages/Trac-0.11dev_r6122-py2.5.egg/trac/ticket/model.py", line 305, in get_changelog
    "ORDER BY time", (self.id,  str(self.id), self.id))
  File "/usr/lib/python2.5/site-packages/Trac-0.11dev_r6122-py2.5.egg/trac/db/util.py", line 50, in execute
    return self.cursor.execute(sql_escape_percent(sql), args)
  File "/usr/lib/python2.5/site-packages/Trac-0.11dev_r6122-py2.5.egg/trac/db/util.py", line 50, in execute
    return self.cursor.execute(sql_escape_percent(sql), args)
ProgrammingError: operator does not exist: text = integer
LINE 1: ...mment',null,description,0 FROM attachment WHERE id=327 ORDER...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

}}}
    

Reported by mpech

**Comment by Anteru** [comment]
(Original issue was assigned to gbrandl)

(Original issue 332 last updated on 2008-06-12T22:04:13+00:00)

(Issue automaticaly closed due to status in Bitbucket: resolved)

**Comment by Anteru** [comment]
(Original comment by gbrandl on 2008-06-12T22:04:13+00:00)

Can't reproduce that here.
