### ISSUE TITLE
"cannot use a string pattern on a bytes-like object" with -O encoding

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments-migration-test#1142]
(Original issue 1438 created by cybershadow on 2018-04-11T20:20:45.377846+00:00)

```
$ echo foo | pygmentize -v -O encoding=utf8 

*****************************************************************
An unhandled exception occurred while highlighting.
Please report the whole traceback to the issue tracker at
<https://bitbucket.org/birkenfeld/pygments-main/issues>.
*****************************************************************

Traceback (most recent call last):
  File "/usr/sbin/pygmentize", line 11, in <module>
    load_entry_point('Pygments', 'console_scripts', 'pygmentize')()
  File "/usr/lib/python3.6/site-packages/pygments/cmdline.py", line 543, in main
    return main_inner(popts, args, usage)
  File "/usr/lib/python3.6/site-packages/pygments/cmdline.py", line 408, in main_inner
    lexer = guess_lexer(code, **parsed_opts)
  File "/usr/lib/python3.6/site-packages/pygments/lexers/__init__.py", line 292, in guess_lexer
    ft = get_filetype_from_buffer(_text)
  File "/usr/lib/python3.6/site-packages/pygments/modeline.py", line 35, in get_filetype_from_buffer
    ret = get_filetype_from_line(l)
  File "/usr/lib/python3.6/site-packages/pygments/modeline.py", line 24, in get_filetype_from_line
    m = modeline_re.search(l)
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by Anteru** [comment]
(Original issue 1438 last updated on 2019-05-28T05:03:43.608617+00:00)

(Issue automaticaly closed due to status in Bitbucket: resolved)

**Comment by Anteru** [comment]
(Original comment by cybershadow on 2019-05-25T18:04:37.982418+00:00)

Still a problem in 2.4.0.

**Comment by Anteru** [comment]
(Original comment by Anteru on 2019-05-26T19:05:24.936260+00:00)

```
$ echo foo | pygmentize -v -O encoding=utf8 

*****************************************************************
An unhandled exception occurred while highlighting.
Please report the whole traceback to the issue tracker at
<https://bitbucket.org/birkenfeld/pygments-main/issues>.
*****************************************************************

Traceback (most recent call last):
  File "/usr/sbin/pygmentize", line 11, in <module>
    load_entry_point('Pygments', 'console_scripts', 'pygmentize')()
  File "/usr/lib/python3.6/site-packages/pygments/cmdline.py", line 543, in main
    return main_inner(popts, args, usage)
  File "/usr/lib/python3.6/site-packages/pygments/cmdline.py", line 408, in main_inner
    lexer = guess_lexer(code, **parsed_opts)
  File "/usr/lib/python3.6/site-packages/pygments/lexers/__init__.py", line 292, in guess_lexer
    ft = get_filetype_from_buffer(_text)
  File "/usr/lib/python3.6/site-packages/pygments/modeline.py", line 35, in get_filetype_from_buffer
    ret = get_filetype_from_line(l)
  File "/usr/lib/python3.6/site-packages/pygments/modeline.py", line 24, in get_filetype_from_line
    m = modeline_re.search(l)
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2019-05-27T05:33:26.247981+00:00)

Warrants a patch release?

**Comment by Anteru** [comment]
(Original comment by Anteru on 2019-05-27T06:06:58.002120+00:00)

Sounds like it, too bad I just released 2.4.1. If you want to get a 2.4.2 out of the door this week, go for it :slight_smile:

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2019-05-28T04:39:48.858604+00:00)

Properly decode text in guess_lexer if necessary.

fixes #1438

→ <<cset 76b93403fef7>>

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2019-05-28T05:03:43.590642+00:00)

2\.4.2 is released.
