### ISSUE TITLE
PythonTracebackLexer doesn't properly handle SyntaxErrors or top-level KeyboardInterrupts

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments-migration-test#139]
(Original issue 360 created by None on 2008-08-26T00:22:09+00:00)

`PythonTracebackLexer` assumes all tracebacks start with `Traceback (most recent call last):` and erroneously highlights tracebacks that don't have them:

{{{
>>> :
  File "<stdin>", line 1
    :
    ^
SyntaxError: invalid syntax
>>> 
KeyboardInterrupt
>>>
}}}

Using `TerminalFormatter`, Pygments highlights both with underlined red text.

Also, just to be clear, I'm talking about Pygments failing on ''just'' the traceback text above, not including the prompt text. And the `SyntaxError` format isn't specific to the interactive interpreter, though that `KeyboardInterrupt` format probably is.

Reported by guest

**Comment by Anteru** [comment]
(Original issue was assigned to thatch)

(Original issue 360 last updated on 2008-09-21T16:46:20+00:00)

(Issue automaticaly closed due to status in Bitbucket: resolved)

**Comment by Anteru** [comment]
(Original comment by thatch on 2008-09-21T16:46:20+00:00)

For future reference, the newline issue has been reported as http://bugs.python.org/issue3684

**Comment by Anteru** [comment]
(Original comment by gbrandl on 2008-09-11T22:33:37+00:00)

Merged to main.

**Comment by Anteru** [comment]
(Original comment by thatch on 2008-08-26T01:35:46+00:00)

Basic support in [1b0be8c5b60d].  The newline issue in the first comment appears to be a different issue in traceback formatting.

**Comment by Anteru** [comment]
(Original comment by None on 2008-08-26T00:44:54+00:00)

Also, it currently seems to insert newlines in tracebacks that have code ending with a plus sign:
{{{
>>> 1+
  File "<stdin>", line 1
    1+
     
^
SyntaxError: invalid syntax
}}}

Compared to the original:
{{{
>>> 1+
  File "<stdin>", line 1
    1+
     ^
SyntaxError: invalid syntax
}}}

I'm not sure if this would go away if it properly recognized the traceback.
