### ISSUE TITLE
Codetags Broken

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments-migration-test#3]
(Original issue 107 created by None on 2006-09-24T14:35:43+00:00)

= python "Oops" trying to use code-tags =
 
I'm using the version as checked out from the repository [1434].
{{{
Python traceback
Traceback (most recent call last):
  File "/usr/local/lib/python2.4/site-packages/trac/web/modpython_frontend.py", line 206, in handler
    dispatch_request(mpr.path_info, mpr, env)
  File "/usr/local/lib/python2.4/site-packages/trac/web/main.py", line 139, in dispatch_request
    dispatcher.dispatch(req)
  File "/usr/local/lib/python2.4/site-packages/trac/web/main.py", line 107, in dispatch
    resp = chosen_handler.process_request(req)
  File "build/bdist.freebsd-5.3-RELEASE-i386/egg/codetags/__init__.py", line 38, in process_request
  File "build/bdist.freebsd-5.3-RELEASE-i386/egg/codetags/indexer.py", line 152, in get_taglist
  File "build/bdist.freebsd-5.3-RELEASE-i386/egg/codetags/indexer.py", line 146, in get_new_tags
NameError: global name 'result' is not defined
}}}
See it crash live here:
  http://www.darkarts.co.za/projects/unwimp/codetags

Reported by entropy

**Comment by Anteru** [comment]
(Original issue 107 last updated on 2007-02-28T16:23:53+00:00)

(Issue automaticaly closed due to status in Bitbucket: resolved)

**Comment by Anteru** [comment]
(Original comment by gbrandl on 2006-09-25T13:38:10+00:00)

Fixed in r1897.
