### ISSUE TITLE
TypeError when guessing the lexer of a text that begins with a dot

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments-migration-test#325]
(Original issue 618 created by marcio_ on 2010-11-25T20:28:47.812522+00:00)

If I try to guess the lexer for a text that begins with a dot, using Pygments 1.3.1 with Python 2.7, I get the following error:

{{{
#!text

$ echo .a | pygmentize -g                                                
Traceback (most recent call last):
  File "/usr/local/bin/pygmentize", line 9, in <module>
    load_entry_point('Pygments==1.3.1', 'console_scripts', 'pygmentize')()
  File "/usr/local/lib/python2.7/site-packages/Pygments-1.3.1-py2.6.egg/pygments/cmdline.py", line 387, in main
    lexer = guess_lexer(code)
  File "/usr/local/lib/python2.7/site-packages/Pygments-1.3.1-py2.6.egg/pygments/lexers/__init__.py", line 199, in guess_lexer
    rv = lexer.analyse_text(_text)
  File "/usr/local/lib/python2.7/site-packages/Pygments-1.3.1-py2.6.egg/pygments/util.py", line 116, in text_analyse
    return min(1.0, max(0.0, float(rv)))
TypeError: float() argument must be a string or a number
}}}

**Comment by Anteru** [comment]
(Original issue 618 last updated on 2011-10-07T20:44:06.396464+00:00)

(Issue automaticaly closed due to status in Bitbucket: resolved)

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2010-11-26T09:08:25.817975+00:00)

Fixed in <<changeset 92355db12206>>. Thanks!

**Comment by Anteru** [comment]
(Original comment by garyposter on 2011-08-02T20:45:00.076054+00:00)

Hi Georg.  Unfortunately, the change you made catches ValueErrors, and this is a TypeError, so it is still a problem:

pygments/util.py
{{{
119        try:
120            return min(1.0, max(0.0, float(rv)))
121        except ValueError:
122            return 0.0
}}}

Simply changing line 121 to {{{except TypeError:}}} looks correct to me, though you could always catch both.

I'd love to see this resolved and released; if there is something I can do to help this along, please let me know.

Thank you

Gary

**Comment by Anteru** [comment]
(Original comment by benji_york on 2011-10-07T20:44:06.384098+00:00)

This was fixed by a recent pull.
