### ISSUE TITLE
obj-c lexer fails on certain files

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments-migration-test#400]
(Original issue 693 created by tmm1 on 2011-08-16T22:18:04.651042+00:00)

{{{
>>> import pygments, pygments.lexers, pygments.formatters

>>> pygments.highlight("-initInManagedObjectContext:(NSManagedObjectContext*)aContext withUser:(User*)aUser\n", pygments.lexers.get_lexer_by_name("objective-c"), pygments.formatters.get_formatter_by_name("html"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pygments/pygments/__init__.py", line 86, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "pygments/pygments/__init__.py", line 66, in format
    formatter.format(tokens, realoutfile)
  File "pygments/pygments/formatter.py", line 92, in format
    return self.format_unencoded(tokensource, outfile)
  File "pygments/pygments/formatters/html.py", line 749, in format_unencoded
    for t, piece in source:
  File "pygments/pygments/formatters/html.py", line 618, in _wrap_div
    for tup in inner:
  File "pygments/pygments/formatters/html.py", line 631, in _wrap_pre
    for tup in inner:
  File "pygments/pygments/formatters/html.py", line 649, in _format_lines
    for ttype, value in tokensource:
  File "pygments/pygments/lexer.py", line 162, in streamer
    for i, t, v in self.get_tokens_unprocessed(text):
  File "pygments/pygments/lexer.py", line 503, in get_tokens_unprocessed
    for item in action(self, m):
  File "pygments/pygments/lexer.py", line 280, in callback
    match.group(i + 1)), ctx):
  File "pygments/pygments/lexer.py", line 328, in callback
    for i, t, v in lx.get_tokens_unprocessed(match.group(), **gt_kwargs):
  File "pygments/pygments/lexer.py", line 498, in get_tokens_unprocessed
    m = rexmatch(text, pos)
TypeError: expected string or buffer

}}}

**Comment by Anteru** [comment]
(Original issue 693 last updated on 2012-02-05T07:58:12.092353+00:00)

(Issue automaticaly closed due to status in Bitbucket: resolved)

**Comment by Anteru** [comment]
(Original comment by tmm1 on 2011-08-16T22:19:04.555802+00:00)

This works on pygments 1.4, but fails on trunk.

**Comment by Anteru** [comment]
(Original comment by tmm1 on 2011-08-18T18:52:19.168423+00:00)

Here's another file that exposes this issue: https://raw.github.com/stevedekorte/SGMLKit/master/SGML/SGMLDocument.h

**Comment by Anteru** [comment]
(Original comment by apepper on 2011-10-05T09:56:33.836145+00:00)

I ran into the same issue. Here my minimal example:
{{{
$ echo "+ foo;" | pygmentize -l objectivec
*** Error while highlighting:
TypeError: expected string or buffer
   (file "/Library/Python/2.6/site-packages/Pygments-1.4dev_20111005-py2.6.egg/pygments/lexer.py", line 497, in get_tokens_unprocessed)
}}}

It seems, that methods with NO stated arguments will fail.

I also did some bisecting and nailed it to changes in cf606e81df8a and <<issue 638>> .

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2012-02-05T07:58:12.089679+00:00)

Closes #693: fix ObjectiveC lexer throwing errors sometimes because bygroups() does not skip empty groups for callbacks.

→ <<cset 7b71b794ee8a>>
