### ISSUE TITLE
Bad GasLexer causes guess_lexer to fail

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments-migration-test#411]
(Original issue 704 created by eddiec on 2011-09-21T21:58:11.837493+00:00)

The current `analyse_text` method of `GasLexer` mistakenly returns a regular expression and causes `guess_lexer` to fail:

{{{
#!python

>>> from pygments.lexers import guess_lexer
>>> guess_lexer('.code {}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/caoyi3/Development/hashdown/venv/lib/python2.6/site-packages/pygments/lexers/__init__.py", line 199, in guess_lexer
    rv = lexer.analyse_text(_text)
  File "/Users/caoyi3/Development/hashdown/venv/lib/python2.6/site-packages/pygments/util.py", line 120, in text_analyse
    return min(1.0, max(0.0, float(rv)))
TypeError: float() argument must be a string or a number
}}}

I am including a very simple patch.

**Comment by Anteru** [comment]
(Original issue 704 last updated on 2012-02-05T11:20:37.702899+00:00)

(Issue automaticaly closed due to status in Bitbucket: resolved)

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2012-02-05T11:20:37.691480+00:00)

Already fixed in tip.
