### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0x85 in position 617: invalid start byte 

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments-migration-test#435]
(Original issue 728 created by umpirsky on 2012-01-11T19:29:01.217990+00:00)

This is the error I get:

{{{
#!python

Traceback (most recent call last):
...
    highlight(diff, DiffLexer(), HtmlFormatter()),
  File "/usr/lib/python2.7/dist-packages/pygments/__init__.py", line 86, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/usr/lib/python2.7/dist-packages/pygments/__init__.py", line 45, in lex
    return lexer.get_tokens(code)
  File "/usr/lib/python2.7/dist-packages/pygments/lexer.py", line 148, in get_tokens
    text = text.decode(self.encoding)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x85 in position 617: invalid start byte
}}}

I am rendering this https://github.com/umpirsky/eclipse-templates/commit/3a292de562d8ef9b7b0f92e3f27998f2f66ae4ef diff and the problem is '…' char.

**Comment by Anteru** [comment]
(Original issue 728 last updated on 2012-02-05T08:48:58.100976+00:00)

(Issue automaticaly closed due to status in Bitbucket: resolved)

**Comment by Anteru** [comment]
(Original comment by umpirsky on 2012-01-14T18:48:15.174461+00:00)

Any idea, workaround...?

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2012-02-05T08:48:58.091898+00:00)

If the input isn't UTF-8, you have to give the input encoding to the lexer as an argument.
