### ISSUE TITLE
python 2.4: invalid syntax in sql.py

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments-migration-test#446]
(Original issue 739 created by blacktrash on 2012-02-15T23:08:28.175398+00:00)

{{{
$ python setup.py install --home=~
[...]
byte-compiling /home/username/lib/python/pygments/lexers/sql.py to sql.pyc
  File "/home/username/lib/python/pygments/lexers/sql.py", line 246
    i = yield i
            ^
SyntaxError: invalid syntax
[...]
$ python -V
Python 2.4.3
}}}

This is on my server, and prevents me from using the hg highlight extension because even though the sql lexer is not used it causes a traceback.

**Comment by Anteru** [comment]
(Original issue 739 last updated on 2012-05-08T13:20:16.350033+00:00)

(Issue automaticaly closed due to status in Bitbucket: resolved)

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2012-02-18T07:10:41.156226+00:00)

Closes #739: replace generator-send with custom class to work under 2.4.

→ <<cset 7dfb84f77662>>

**Comment by Anteru** [comment]
(Original comment by blacktrash on 2012-02-19T05:51:43.138591+00:00)

Not so fast ;-)

I now get a different traceback:

{{{
>>> from pygments.lexers import guess_lexer_for_filename
>>> text = open('setup.py').read()[:1024]
>>> guess_lexer_for_filename('setup.py', text)
Traceback (most recent call last):
  File "<stdin>", line 1, in ?
  File "pygments/lexers/__init__.py", line 172, in guess_lexer_for_filename
    for lexer in _iter_lexerclasses():
  File "pygments/lexers/__init__.py", line 147, in _iter_lexerclasses
    _load_lexers(module_name)
  File "pygments/lexers/__init__.py", line 32, in _load_lexers
    mod = __import__(module_name, None, None, ['__all__'])
  File "pygments/lexers/other.py", line 22, in ?
    from pygments.lexers.sql import SqlLexer, MySqlLexer, SqliteConsoleLexer
  File "pygments/lexers/sql.py", line 174, in ?
    class PlPgsqlLexer(PostgresBase, RegexLexer):
  File "pygments/lexers/sql.py", line 185, in PlPgsqlLexer
    tokens = deepcopy(PostgresLexer.tokens)
  File "/usr/lib64/python2.4/copy.py", line 174, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.4/copy.py", line 268, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.4/copy.py", line 174, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.4/copy.py", line 241, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/lib64/python2.4/copy.py", line 174, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.4/copy.py", line 248, in _deepcopy_tuple
    y.append(deepcopy(a, memo))
  File "/usr/lib64/python2.4/copy.py", line 204, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.4/copy.py", line 336, in _reconstruct
    y = callable(*args)
  File "/usr/lib64/python2.4/copy_reg.py", line 92, in __newobj__
    return cls.__new__(cls, *args)
TypeError: function() takes at least 2 arguments (0 given)
>>>
}}}

**Comment by Anteru** [comment]
(Original comment by blacktrash on 2012-02-21T14:52:35.686546+00:00)

If you prefer me to open a separate issue for this, just tell me so. thx

**Comment by Anteru** [comment]
(Original comment by blacktrash on 2012-03-11T14:28:01.806883+00:00)

Any thoughts on this?

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2012-05-08T11:20:51.646342+00:00)

Fixed for #749.

**Comment by Anteru** [comment]
(Original comment by blacktrash on 2012-05-08T13:20:16.213550+00:00)

Confirming it is fixed. thx
