### ISSUE TITLE
test_html_formatter.HtmlFormatterTest.test_valid_output() fails in Pygments 1.5

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments-migration-test#454]
(Original issue 747 created by arfrever on 2012-03-11T02:18:46.326870+00:00)

{{{
$ python2.7 tests/run.py
Pygments 1.5 test suite running (Python 2.7.3rc1)...
..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................nsgmls:/etc/sgml/catalog:11:8:E: cannot open "/etc/sgml/sgml-docbook-3.1.cat" (No such file or directory)
nsgmls:/etc/sgml/catalog:12:8:E: cannot open "/etc/sgml/sgml-docbook-4.1.cat" (No such file or directory)
nsgmls:/etc/sgml/catalog:13:8:E: cannot open "/etc/sgml/sgml-docbook-4.0.cat" (No such file or directory)
F....................................
======================================================================
FAIL: test_valid_output (test_html_formatter.HtmlFormatterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/Pygments-1.5/tests/test_html_formatter.py", line 128, in test_valid_output
    self.failIf(ret, 'nsgmls run reported errors')
AssertionError: nsgmls run reported errors

----------------------------------------------------------------------
Ran 771 tests in 37.166s

FAILED (failures=1)
}}}

**Comment by Anteru** [comment]
(Original issue 747 last updated on 2012-03-11T13:54:59.516201+00:00)

(Issue automaticaly closed due to status in Bitbucket: invalid)

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2012-03-11T07:25:09.819570+00:00)

I can't reproduce this here with Gentoo's opensp-1.5.2-r2 and openjade-1.3.2-r3.  I also don't get the warnings about docbook files.

At the very least, I need any output that nsgmls gives you.  For this, the tests will now print the output in case of failure as of <<changeset 183947d26024>>.

**Comment by Anteru** [comment]
(Original comment by arfrever on 2012-03-11T08:14:55.644462+00:00)

Apparently manual deletion of 3 entries in /etc/sgml/catalog has fixed this problem.

A more verbose output (with Python 3.2) contained:
{{{
======================================================================
FAIL: test_valid_output (test_html_formatter.HtmlFormatterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pygments-main/build/lib/test/test_html_formatter.py", line 136, in test_valid_output
    self.assertFalse(ret, 'nsgmls run reported errors')
AssertionError: AssertionError: 1 is not false : nsgmls run reported errors
-------------------- >> begin captured stdout << ---------------------
b''

--------------------- >> end captured stdout << ----------------------
}}}

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2012-03-11T13:54:59.507400+00:00)

Thanks for the clarification.
