### ISSUE TITLE
Not compatible with python 2.4

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments-migration-test#456]
(Original issue 749 created by blacktrash on 2012-03-20T09:10:37.078461+00:00)

See #739, but that started out differently. Anyway, guess_lexer_for_filename causes a traceback in Python 2.4:

{{{
Python 2.4.3 (#1, Sep 21 2011, 19:55:41) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-51)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pygments.lexers import guess_lexer_for_filename
>>> text = open('setup.py').read()[:1024]
>>> guess_lexer_for_filename('setup.py', text)
Traceback (most recent call last):
  File "<stdin>", line 1, in ?
  File "pygments/lexers/__init__.py", line 172, in guess_lexer_for_filename
    for lexer in _iter_lexerclasses():
  File "pygments/lexers/__init__.py", line 147, in _iter_lexerclasses
    _load_lexers(module_name)
  File "pygments/lexers/__init__.py", line 32, in _load_lexers
    mod = __import__(module_name, None, None, ['__all__'])
  File "pygments/lexers/other.py", line 22, in ?
    from pygments.lexers.sql import SqlLexer, MySqlLexer, SqliteConsoleLexer
  File "pygments/lexers/sql.py", line 174, in ?
    class PlPgsqlLexer(PostgresBase, RegexLexer):
  File "pygments/lexers/sql.py", line 185, in PlPgsqlLexer
    tokens = deepcopy(PostgresLexer.tokens)
  File "/usr/lib64/python2.4/copy.py", line 174, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.4/copy.py", line 268, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.4/copy.py", line 174, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.4/copy.py", line 241, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/lib64/python2.4/copy.py", line 174, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.4/copy.py", line 248, in _deepcopy_tuple
    y.append(deepcopy(a, memo))
  File "/usr/lib64/python2.4/copy.py", line 204, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.4/copy.py", line 336, in _reconstruct
    y = callable(*args)
  File "/usr/lib64/python2.4/copy_reg.py", line 92, in __newobj__
    return cls.__new__(cls, *args)
TypeError: function() takes at least 2 arguments (0 given)
>>>
}}}

This also makes the mercurial highlight extension incompatible with Python 2.4:
https://bitbucket.org/mirror/mercurial/src/63a1bed65fa3/hgext/highlight/highlight.py#cl-41

**Comment by Anteru** [comment]
(Original issue 749 last updated on 2012-05-08T13:21:25.688988+00:00)

(Issue automaticaly closed due to status in Bitbucket: resolved)

**Comment by Anteru** [comment]
(Original comment by blacktrash on 2012-03-20T09:18:04.768090+00:00)

See also:
http://mercurial.selenic.com/bts/issue3325

**Comment by Anteru** [comment]
(Original comment by blacktrash on 2012-03-26T08:18:57.192550+00:00)

deepcopy is indeed the problem. Bisected to first bad changeset https://bitbucket.org/birkenfeld/pygments-main/changeset/5f511394ab35 with
{{{
python2.4 setup.py install --home=~ && python2.4 setup.py clean -a && python2.4 -c 'from pygments.lexers import guess_lexer_for_filename; print guess_lexer_for_filename("setup.py", open("setup.py").read())'
}}}

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2012-05-08T11:20:07.941950+00:00)

Closes #749: get rid of deepcopy usage to restore 2.4 compatibility

→ <<cset 5b45626edb4c>>

**Comment by Anteru** [comment]
(Original comment by blacktrash on 2012-05-08T13:21:25.673850+00:00)

thanks a lot!

**Comment by Anteru** [comment]
(Original comment by tshatch on 2012-11-06T16:00:22.133774+00:00)

Issue #814 was marked as a duplicate of this issue.
