### ISSUE TITLE
Doesn't install with Jython

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments-migration-test#493]
(Original issue 786 created by rtbf*q4L6ZmlUSAa_T902yjBPDQ on 2012-06-25T20:50:02.502913+00:00)

I'm using Jython 2.7a2, the latest.

I've set up a Jython virtualenv, and run 'pip install pygments'. It fails at the following stage:

```
byte-compiling /home/ian/Applications/jython-env/Lib/site-packages/pygments/lexers/_vimbuiltins.py to _vimbuiltins$py.class

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ian/Applications/jython-env/build/pygments/setup.py", line 61, in <module>
    setup(
  File "/home/ian/Applications/jython2.7a2/Lib/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/home/ian/Applications/jython2.7a2/Lib/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/home/ian/Applications/jython2.7a2/Lib/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/ian/Applications/jython2.7a2/Lib/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/ian/Applications/jython-env/Lib/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/install.py", line 56, in run
  File "/home/ian/Applications/jython2.7a2/Lib/distutils/command/install.py", line 517, in run
    self.run_command(cmd_name)
  File "/home/ian/Applications/jython2.7a2/Lib/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/home/ian/Applications/jython2.7a2/Lib/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/ian/Applications/jython-env/Lib/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/install_lib.py", line 24, in run
  File "/home/ian/Applications/jython2.7a2/Lib/distutils/command/install_lib.py", line 136, in byte_compile
    byte_compile(files, optimize=0,
  File "/home/ian/Applications/jython2.7a2/Lib/distutils/util.py", line 567, in byte_compile
    compile(file, cfile, dfile)
  File "/home/ian/Applications/jython2.7a2/Lib/py_compile.py", line 96, in compile
    _py_compile.compile(file, cfile, dfile)
  File "/home/ian/Applications/jython2.7a2/Lib/py_compile.py", line 96, in compile
    _py_compile.compile(file, cfile, dfile)
        at org.python.objectweb.asm.MethodWriter.a(Unknown Source)
        at org.python.objectweb.asm.ClassWriter.toByteArray(Unknown Source)
        at org.python.compiler.ClassFile.write(ClassFile.java:124)
        at org.python.compiler.Module.write(Module.java:618)
        at org.python.compiler.Module.compile(Module.java:674)
        at org.python.core.imp.compileSource(imp.java:330)
        at org.python.core.imp.compileSource(imp.java:252)
        at org.python.modules._py_compile.compile(_py_compile.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)

java.lang.RuntimeException: java.lang.RuntimeException: Method code too large!
```

Jython can't compile methods over a certain size. One solution is to import pycimport; this requires that a pyc file has been generated by CPython.

**Comment by Anteru** [comment]
(Original issue 786 last updated on 2014-10-07T21:59:30.233463+00:00)

(Issue automaticaly closed due to status in Bitbucket: resolved)

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2012-08-19T09:14:06.185831+00:00)

Hmm, I'd rather consider this a bug in Jython.

**Comment by Anteru** [comment]
(Original comment by tshatch on 2012-08-28T15:25:03.539096+00:00)

Yes, it's actually a limitation of the JVM, not just Jython however.  In this case, there's a fairly trivial workaround in a file that humans aren't intended to edit, so I think we should do it.

ref: http://docs.oracle.com/javase/specs/jvms/se5.0/html/ClassFile.doc.html#88659

_vimbuiltins.py defines several large tables, and those tables combined are too large for a single method in Java.  Individually though, they're fine.

Pushed http://code.timhatch.com/hg/pygments-tim/rev/913a59849ec1

**Comment by Anteru** [comment]
(Original comment by tshatch on 2012-11-01T16:05:36.455351+00:00)

I believe this should be fixed now -- can you confirm?

**Comment by Anteru** [comment]
(Original comment by tshatch on 2012-11-12T23:05:05.993545+00:00)

I believe I already fixed this -- if not, please reopen.

**Comment by Anteru** [comment]
(Original comment by rtbf*q4L6ZmlUSAa_T902yjBPDQ on 2012-12-27T10:46:36.808788+00:00)

I just tested it again and got the same error. Steps to reproduce:

1. Download and install Jython 2.7a2 from <http://www.jython.org/downloads.html>.
2. Download and install pip in a virtualenv according to <http://www.pip-installer.org/en/latest/installing.html>.
3. source the virtualenv and do `pip install pygments`.

The installation process will error out with "java.lang.RuntimeException: Method code too large!"

**Comment by Anteru** [comment]
(Original comment by tmortagne on 2013-01-10T07:59:46.527169+00:00)

Hi guys, note that I'm using Pygments from Java since a while but I'm still using Jython 2.5.3 and I don't have any issue. I just wrote http://pygments.org/docs/java/ to indicate how I use it if you want to check. Maybe there is something wrong in 2.7 or maybe it's with a parser or a serializer I never used myself yet (did ot checked the detail of your error).

**Comment by Anteru** [comment]
(Original comment by fengxx on 2013-01-14T08:29:17.521872+00:00)

I can not reproduce the error use Jython 2.7a2 with either JDK  1.7.0_05 or 1.6.0_33

**Comment by Anteru** [comment]
(Original comment by rtbf*q4L6ZmlUSAa_T902yjBPDQ on 2013-01-14T22:28:25.571743+00:00)

Well I have 1.6.0_24 (Debian Wheezy) so maybe it's been fixed in newer versions?

**Comment by Anteru** [comment]
(Original comment by tmortagne on 2013-01-22T14:45:29.817203+00:00)

Actually someone reported me that he had the exact same issue but only with the Vim language so it's not a general Pygments issue (not a Pygments issue at all anyway) but something Jython or the JVM does not like about one of the Vim lexer methods when converted to Java bytecode.

**Comment by Anteru** [comment]
(Original comment by tmortagne on 2013-01-22T15:01:00.086034+00:00)

By the way, see http://bugs.jython.org/issue1891 for more details on Jython side about the issue.

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2014-10-07T21:59:30.246382+00:00)

From the Jython issue:

"For the specific case of Pygments, Jython 2.7 trunk now compiles this just fine."
