### ISSUE TITLE
error when using "diff" lexer

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments-migration-test#521]
(Original issue 814 created by djschny on 2012-10-18T22:35:16.709464+00:00)

The following error is received when using Pygments 1.5 and Python 2.4.3. It happens regardless of input data.

```
#!pytb
[rschneider@pelennor ~]$ pygmentize -l diff -O noclasses=True -f html gitlog.diff 
Traceback (most recent call last):
  File "/usr/bin/pygmentize", line 7, in ?
    sys.exit(
  File "/usr/lib/python2.4/site-packages/Pygments-1.5-py2.4.egg/pygments/cmdline.py", line 350, in main
    lexer = get_lexer_by_name(lexer, **parsed_opts)
  File "/usr/lib/python2.4/site-packages/Pygments-1.5-py2.4.egg/pygments/lexers/__init__.py", line 74, in get_lexer_by_name
    _load_lexers(module_name)
  File "/usr/lib/python2.4/site-packages/Pygments-1.5-py2.4.egg/pygments/lexers/__init__.py", line 32, in _load_lexers
    mod = __import__(module_name, None, None, ['__all__'])
  File "/usr/lib/python2.4/site-packages/Pygments-1.5-py2.4.egg/pygments/lexers/text.py", line 20, in ?
    from pygments.lexers.other import BashLexer
  File "/usr/lib/python2.4/site-packages/Pygments-1.5-py2.4.egg/pygments/lexers/other.py", line 22, in ?
    from pygments.lexers.sql import SqlLexer, MySqlLexer, SqliteConsoleLexer
  File "/usr/lib/python2.4/site-packages/Pygments-1.5-py2.4.egg/pygments/lexers/sql.py", line 174, in ?
    class PlPgsqlLexer(PostgresBase, RegexLexer):
  File "/usr/lib/python2.4/site-packages/Pygments-1.5-py2.4.egg/pygments/lexers/sql.py", line 185, in PlPgsqlLexer
    tokens = deepcopy(PostgresLexer.tokens)
  File "/usr/lib64/python2.4/copy.py", line 174, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.4/copy.py", line 268, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.4/copy.py", line 174, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.4/copy.py", line 241, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/lib64/python2.4/copy.py", line 174, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.4/copy.py", line 248, in _deepcopy_tuple
    y.append(deepcopy(a, memo))
  File "/usr/lib64/python2.4/copy.py", line 204, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.4/copy.py", line 336, in _reconstruct
    y = callable(*args)
  File "/usr/lib64/python2.4/copy_reg.py", line 92, in __newobj__
    return cls.__new__(cls, *args)
TypeError: function() takes at least 2 arguments (0 given)
```

**Comment by Anteru** [comment]
(Original issue 814 last updated on 2012-11-06T16:00:22.135368+00:00)

(Issue automaticaly closed due to status in Bitbucket: duplicate)

**Comment by Anteru** [comment]
(Original comment by tshatch on 2012-11-06T16:00:02.679467+00:00)

Duplicate of #749, this should be fixed in the next released version (Real Soon Now). If you need to cherry-pick, it's [5b45626edb4c](https://bitbucket.org/birkenfeld/pygments-main/changeset/5b45626edb4c)

**Comment by Anteru** [comment]
(Original comment by tshatch on 2012-11-06T16:00:22.152240+00:00)

Duplicate of #749.
