### ISSUE TITLE
PowerShellLexer sometimes fails on test_lexer_classes()

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments-migration-test#577]
(Original issue 870 created by roskakori on 2013-05-09T23:34:02.174821+00:00)

When running `make test` sometimes the `PowerShellLexer` fails in `test_lexer_classes()`: 

```

ERROR: test_basic_api.test_lexer_classes(<class 'pygments.lexers.shell.PowerShellLexer'>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyg/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/agi/workspace/pygments-main/tests/test_basic_api.py", line 67, in verify
    tokens = list(inst.get_tokens(test_content))
  File "../pygments/lexer.py", line 186, in streamer
    for i, t, v in self.get_tokens_unprocessed(text):
  File "../pygments/lexer.py", line 604, in get_tokens_unprocessed
    statetokens = tokendefs[statestack[-1]]
IndexError: list index out of range
```

As the `test_content` is random, this cannot be easily reproduced by just running the test. So I dumped `test_content` to a file and attached it so you can reproduce it from the console:

```bash
$ ./pygmentize -f html -O full,style=emacs -l powershell /tmp/test_content.txt >/tmp/example.html
```

This results in:

```
*** Error while highlighting:
IndexError: list index out of range
   (file "/Users/agi/workspace/pygments-main/pygments/lexer.py", line 604, in get_tokens_unprocessed)
```

**Comment by Anteru** [comment]
(Original issue 870 last updated on 2013-05-09T23:56:39.653440+00:00)

(Issue automaticaly closed due to status in Bitbucket: duplicate)

**Comment by Anteru** [comment]
(Original comment by tshatch on 2013-05-09T23:56:39.773960+00:00)

Duplicate of #869.
