### ISSUE TITLE
Q: using() to delegate to sub-lexers not working

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments-migration-test#830]
(Original issue 1123 created by thomas_beale on 2015-06-30T07:50:30.421224+00:00)

I have created a lexer for the Archetype Definition Language (ADL), which is a simple backbone heading syntax within which 3 other 'real' syntaxes can appear. I have built Python classes for these languages and tested them, they work as expected.

However I cannot get the delegating code to work for the outer language. A simplified version of it looks as follows (see attachment for full lexer):

```
    tokens = {
        'whitespace': [
            ...
        ],
        'string': [
            inherit,
        ],
        'odin_section': [
            (r'^[ \t]+.*\n', using(OdinLexer)),
            ('', Text, '#pop'),
        ],
        'cadl_section': [
            (r'^[ \t]+.*\n', using(CadlLexer)),
            ('', Text, '#pop'),
        ],
        'rules_section': [
            (r'^[ \t]+.*\n', using(RulesLexer)),
            ('', Text, '#pop'),
        ],
        'metadata': [
            ...
        ],
        'root': [
            (r'^(archetype|template|template_overlay|operational_template|speciali[sz]e)', Generic.Heading),
            (r'^(language|description|ontology|terminology|annotations|revision_history)[ \t]*$', Generic.Heading, 'odin_section'),
            (r'^(definition)[ \t]*$', Generic.Heading, 'cadl_section'),
            (r'^(rules)[ \t]*$', Generic.Heading, 'rules_section'),
            (r'[ \t]*([a-zA-Z]\w+(\.[a-zA-Z]\w+)*::)?[a-zA-Z]\w+(-[a-zA-Z]\w+){2}\.\w+(-\w+)*\.v\d+(\.\d+){,2}((-[a-z]+)(\.\d+)?)?', Generic.Namespace), # archetype id
            (r'[ \t]*\(', Punctuation, 'metadata'),
            include('whitespace'),
        ],
    }
```

The result I get in HTML is that the outer keywords have been matched correctly, but that all the content that is supposedly processed by the sub-lexers is output in 'error' highlighting style. I can't tell whether the method of passing the text to the sub-lexers is wrong, or the calling approach or what.

As far as I can see, I am following the same approach documented in the Pygments site documentation.

The test_basic.adls file is the one that corresponds to the outer 'adl' syntax, and is the one that relies on calling other lexers working. The .odin and .cadl files work fine.

Any help appreciated.

**Comment by Anteru** [comment]
(Original issue 1123 last updated on 2015-11-01T11:49:53.478856+00:00)

(Issue automaticaly closed due to status in Bitbucket: resolved)

**Comment by Anteru** [comment]
(Original comment by dscorbett on 2015-06-30T13:33:34.609331+00:00)

The regexes which lead to the states `odin_section`, `codl_section`, and `rules_section` end with `$`, which matches before the newline. Each of those states only delegates to sublexers if their regexes match, all of which begin with `^`. The position right before a newline and after a keyword will never be the beginning of a line. You should change `$` to `\n` or whatever counts as a newline in this language.

**Comment by Anteru** [comment]
(Original comment by thomas_beale on 2015-06-30T15:52:20.656460+00:00)

Yes that was it - I was aware of that exact problem and fixed it in the lines where the sub-lexers are invoke but missed the correction in the root state. So much for staring at code for 2h!

It works nicely now, thanks very much for taking the time to look. 

I will do some testing, and pretty soon I should have a decent version of this language. Can I offer it to the main project as a pull request? It would be just the language.py file plus some example files, i.e. no changes to any of the main software as such.

**Comment by Anteru** [comment]
(Original comment by thomas_beale on 2015-06-30T16:49:31.923214+00:00)

Related question on delegating syntax (at this point I have to say I am not a Python-knowledgeable person) ... I need to delegate into a sub-lexer at a different state than 'root'. 

The documentation implies I can do this:

```
            ('some pattern', Text, using(OdinLexer, state='string')),
```

the `state='string'` bit compiles ok, but when I run it I get this:

```
$ ./pygmentize -v -O full -f html -o /tmp/adl.html tests/examplefiles/example.adls

*****************************************************************
An unhandled exception occurred while highlighting.
Please report the whole traceback to the issue tracker at
<https://bitbucket.org/birkenfeld/pygments-main/issues>.
*****************************************************************

Traceback (most recent call last):
  File "./pygmentize", line 6, in <module>
    sys.exit(pygments.cmdline.main(sys.argv))
  File "/cygdrive/c/dev/utilities/pygments-main/pygments/cmdline.py", line 503, in main
    return main_inner(popts, args, usage)
  File "/cygdrive/c/dev/utilities/pygments-main/pygments/cmdline.py", line 354, in main_inner
    lexer = get_lexer_for_filename(infn, code, **parsed_opts)
  File "/cygdrive/c/dev/utilities/pygments-main/pygments/lexers/__init__.py", line 150, in get_lexer_for_filename
    return res(**options)
  File "/cygdrive/c/dev/utilities/pygments-main/pygments/lexer.py", line 581, in __call__
    cls._tokens = cls.process_tokendef('', cls.get_tokendefs())
  File "/cygdrive/c/dev/utilities/pygments-main/pygments/lexer.py", line 520, in process_tokendef
    cls._process_state(tokendefs, processed, state)
  File "/cygdrive/c/dev/utilities/pygments-main/pygments/lexer.py", line 510, in _process_state
    unprocessed, processed)
  File "/cygdrive/c/dev/utilities/pygments-main/pygments/lexer.py", line 469, in _process_new_state
    assert False, 'unknown new state def %r' % new_state
AssertionError: unknown new state def <function callback at 0x6ffff80ac08>
```

This seems to be complaining about the new state, but I don't understand why. OdinLexer does have a 'string' state.

**Comment by Anteru** [comment]
(Original comment by tshatch on 2015-11-01T00:54:19.500937+00:00)

Sorry for the delay; 'using' is only allowed in the 2nd position.  You need to match the entire chunk and send it at once, or go to another state like you have above for `odin_section` that delegates until some delimiter is reached.

**Comment by Anteru** [comment]
(Original comment by thomas_beale on 2015-11-01T11:49:53.488909+00:00)

Corrected version works and was later incorporated via pull request.
