### ISSUE TITLE
SPARQL lexer error

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments-migration-test#943]
(Original issue 1236 created by jmakeig on 2016-05-04T20:53:26.573532+00:00)

Environment:

* Pygments (2.1.3)
* Python (2.7.10)
* OS X 10.11.4 (15E65)

Input: 

```
#!sparql

PREFIX db: <http://dbpedia.org/resource/>
PREFIX onto: <http://dbpedia.org/ontology/>

SELECT ?p ?o
WHERE 
  { db:Danny_Kaye ?p ?o 
  }
```

Shell script:

```
pygmentize -l sparql -f html -O 'full,style=default' -v
```

Error:

```

*****************************************************************
An unhandled exception occurred while highlighting.
Please report the whole traceback to the issue tracker at
<https://bitbucket.org/birkenfeld/pygments-main/issues>.
*****************************************************************

Traceback (most recent call last):
  File "/usr/local/bin/pygmentize", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/pygments/cmdline.py", line 504, in main
    return main_inner(popts, args, usage)
  File "/Library/Python/2.7/site-packages/pygments/cmdline.py", line 324, in main_inner
    lexer = get_lexer_by_name(lexername, **parsed_opts)
  File "/Library/Python/2.7/site-packages/pygments/lexers/__init__.py", line 88, in get_lexer_by_name
    return _lexer_cache[name](**options)
  File "/Library/Python/2.7/site-packages/pygments/lexer.py", line 580, in __call__
    cls._tokens = cls.process_tokendef('', cls.get_tokendefs())
  File "/Library/Python/2.7/site-packages/pygments/lexer.py", line 519, in process_tokendef
    cls._process_state(tokendefs, processed, state)
  File "/Library/Python/2.7/site-packages/pygments/lexer.py", line 501, in _process_state
    (tdef[0], state, cls, err))
ValueError: uncompilable regex u'(_:[0-9a-zA-Z\xc0-\xd6\xd8-\xf6\xf8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd\U00010000-\U000effff_](?:[a-zA-Z\xc0-\xd6\xd8-\xf6\xf8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd\U00010000-\U000effff_\\-0-9\xb7\u0300-\u036f\u203f-\u2040.]*[a-zA-Z\xc0-\xd6\xd8-\xf6\xf8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd\U00010000-\U000effff_\\-0-9\xb7\u0300-\u036f\u203f-\u2040])?)' in state 'root' of <class 'pygments.lexers.rdf.SparqlLexer'>: bad character range
```

**Comment by Anteru** [comment]
(Original issue 1236 last updated on 2017-01-18T06:18:33.942630+00:00)

(Issue automaticaly closed due to status in Bitbucket: resolved)

**Comment by Anteru** [comment]
(Original comment by tshatch on 2016-06-01T08:13:53.367750+00:00)

This was "fixed" in [60afc531aa2b] which will be available in the 2.2 release soon.

**Comment by Anteru** [comment]
(Original comment by evzijst on 2016-12-30T17:44:06.976456+00:00)

Any updates on 2.2? This is affecting Bitbucket (we use Pygments) and our users are reporting this. We could cherry-pick the patch, but it's rather big.

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2017-01-18T06:18:33.844540+00:00)

Next weekend is looking good for a Pygments release. Sorry for the delays!
